---
version: "3.9"
services:
  rag-api:
    build: .
    container_name: rag_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data # Mount pre-embedded FAISS index and docs
    restart: unless-stopped
